name: Deploy Azure Functions (.NET 8 Isolated + Playwright)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # (valfritt) se filstrukturen för att verifiera vägen
      - name: List files
        run: |
          echo "Repo root:"
          dir
          echo "Project folder:"
          dir b-skrap

      - name: Restore
        working-directory: ./b-skrap
        run: dotnet restore

      - name: Build (Release)
        working-directory: ./b-skrap
        run: dotnet build --configuration Release --no-restore

      - name: Install Playwright browsers
        working-directory: ./b-skrap
        shell: powershell
        run: |
          $script = ".\bin\Release\net8.0\playwright.ps1"
          if (!(Test-Path $script)) { throw "playwright.ps1 not found at $script" }
          powershell -ExecutionPolicy Bypass -File $script install

      - name: Publish (zip)
        working-directory: ./b-skrap
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: b-skrap             # <— ditt Function App-namn
          package: ./b-skrap/publish    # <— pekar på publish-mappen ovan
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
