name: Deploy Azure Function (b-skrap, .NET 8 Isolated + Playwright on Linux)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # (valfritt) se struktur vid felsök
      - name: List files
        run: |
          echo "Repo root:" && ls -la
          echo "Project folder:" && ls -la b-skrap

      - name: Restore
        working-directory: ./b-skrap
        run: dotnet restore

      - name: Build (Release)
        working-directory: ./b-skrap
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        working-directory: ./b-skrap
        run: dotnet publish --configuration Release --output ./publish

      # Installera Chromium + deps i publish-mappen (Playwright på Linux)
      - name: Install Playwright (Linux, .NET)
        working-directory: ./b-skrap
        run: |
          # Låt webbläsarna hamna i publish/playwright-browsers så följer de med deployen
          export PLAYWRIGHT_BROWSERS_PATH=./publish/playwright-browsers

          # Kör .NET-playwright-scriptet som skapas vid builden
          if [ -f "./bin/Release/net8.0/playwright.sh" ]; then
            bash ./bin/Release/net8.0/playwright.sh install --with-deps chromium
          else
            echo "playwright.sh not found. Is 'Microsoft.Playwright' referenced in the .csproj?"
            exit 1
          fi

      - name: Deploy to Azure Functions (Linux)
        uses: azure/functions-action@v1
        with:
          app-name: b-skrap
          package: ./b-skrap/publish
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_LINUX }}
