name: Deploy Azure Functions (.NET 8 Isolated + Playwright)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # (valfritt) se filstrukturen för att verifiera vägen
      - name: List files
        run: |
          echo "Repo root:"
          dir
          echo "Project folder:"
          dir b-skrap

      - name: Restore
        working-directory: ./b-skrap
        run: dotnet restore

      - name: Build (Release)
        working-directory: ./b-skrap
        run: dotnet build --configuration Release --no-restore

      - name: Publish (Release)
        working-directory: ./b-skrap
        run: dotnet publish --configuration Release --output ./publish

      - name: Install Playwright browsers into publish folder
        working-directory: ./b-skrap/publish
        shell: powershell
        run: |
          if (Test-Path ".\playwright.ps1") {
            powershell -ExecutionPolicy Bypass -File .\playwright.ps1 install
          } else {
            Write-Host "playwright.ps1 not found in publish/. Falling back to global CLI..."
            dotnet tool install --global Microsoft.Playwright.CLI
            $env:PATH += ";$env:USERPROFILE\.dotnet\tools"
            playwright install chromium
          }

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: b-skrap             # <— ditt Function App-namn
          package: ./b-skrap/publish    # <— pekar på publish-mappen ovan
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
